[build]
  base = "."
  command = "echo 'Skipping build step'"  # 显式跳过构建
  publish = "."                            # 直接发布根目录

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://prestaphy.netlify.app/api/:splat"
  status = 200
  force = true
