[build]
  base = "."
  command = """
    python -m ensurepip --upgrade
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install -r requirements.txt
    npm run build
  """
  publish = "dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://prestaphy.netlify.app/api/:splat"
  status = 200
  force = true
